version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    command: bash -c "rails db:migrate && rails s -b 0.0.0.0"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=postgres'